apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-pod
  labels:
    tier: db-tier
    type: front-end

spec: 
  template:
    metadata:
      name: myapp-pod
      labels:
        tier: db-tier
        type: front-end

    spec: 
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
