apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-pod
  labels:
    tier: db-tier
    type: front-end

spec: 
  template:
    metadata:
      name: myapp-pod
      labels:
        tier: db-tier
        type: front-end

    spec: 
      containers:
        - name: nginx-container
          image: nginx
  replicas: 6
  selector:
    matchLabels:
      type: front-end
    
